# Use official lightweight Python 3.12 image on Debian Trixie
FROM python:3.12-slim-trixie

# Install uv manually in the container
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set the working directory inside the container
WORKDIR /app

# Copy dependency files first
COPY pyproject.toml uv.lock ./

# Force uv sync to use the system environment and install dependencies without building the local package
ENV UV_PROJECT_ENVIRONMENT="/usr/local"
RUN uv sync --locked --no-dev --no-install-project

# Copy the rest of your backend code into the container
COPY . .

# Tell the container to start your FastAPI app using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
